---
name: CI
on: [push]

jobs:
  main:
    name: Default
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          cache: true
          go-version-file: go.mod
      - run: go mod download
      - run: '[[ -z $(go fmt ./...) ]]'
      # - run: go test ./...
      - run: make
